management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  server:
    port: 8080
  endpoint:
    shutdown:
      enabled: true
    health:
      show-components: always
  #      show-details: always
  endpoints:
    web:
      base-path: "/manage"  # endpoint 경로 변경 (URL 경로가 /actuator/{endpoint} 대신 /manage/{endpoint} 로 변경)
      exposure:
        include: "*"
info:
  app:
    name: hello-actuator
    company: sy

logging:
  level:
    hello.controller: debug

server:
  tomcat:
    mbeanregistry:
      enabled: true